export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_ENGREDIENTS = 'INIT_ENGREDIENTS';
export const FECH_INGREDIENTS_FAILD = 'FECH_INGREDIENTS_FAILD';

export const SEND_ORDER = 'SEND_ORDER'
export const SENT_ORDER_SUCCESS = 'SENT_ORDER_SUCCESS';
export const SENT_ORDER_FAIL = 'SENT_ORDER_FAIL';
