export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_ENGREDIENTS = 'INIT_ENGREDIENTS';
export const FECH_INGREDIENTS_FAILD = 'FECH_INGREDIENTS_FAILD';
